name: 'ShapeIt actions'
description: 'ShapeIt actions, to handle Bets and scopes management '
author: 'Samir AMZANI'
github-token:
  action-input:
    input: GITHUB_TOKEN
    is-default: true
  permissions:
    pull-requests: write
    issues: write 
    pull-requests-reason: to create or update PR comment
    issues-reason: to update issues description with the scopes
inputs:
  operation:
    required: true
    description: 'What kind of operation you want to perform'
    default: 'add-scope'
  scopes-keyword:
    required: true
    description: 'Keyword to use in the bet to identify the scopes'
    default: 'Related to'
  scopes-title:
    required: true
    description: 'Scope header title to use the bets'
    default: 'Scope'
  GITHUB_TOKEN:
    description: "The GitHub access token (e.g. secrets.GITHUB_TOKEN) used to create or update the comment. This defaults to {{ github.token }}."
    default: "${{ github.token }}"
    required: false
outputs:
  message:
    description: 'The message to display'
runs:
  using: 'node16'
  main: 'dist/index.js'
